#!/bin/bash
set -e


if [[ -e " source $HOME/.zshenv" ]]; then
    source $HOME/.zshenv
fi

T4D_ROOT_PATH="${ZDOTDIR:-$HOME/.tools4dev}"

if [[ "$(uname -a | grep -Eo 'RELEASE_ARM64' | uniq)" == "RELEASE_ARM64" ]]; then
    abrew(){
        arch -arm64 brew $*
    }
else
    abrew(){
        brew $*
    }
fi

if [[ -e "$T4D_ROOT_PATH/src/.git" ]]; then
    _branch="${1:-develop}"
    _OLDPWD=$PWD
    CHPWD=1
    cd "$T4D_ROOT_PATH/src"
    git checkout $_branch
    git pull
    CHPWD=0
    cd $_OLDPWD &> /dev/null
else
    abrew update
    abrew reinstall ${1:-tools4dev} ${@:2}
fi

if [[ -e "$T4D_ROOT_PATH/manifest.xml" ]]; then
    TEAM_PATH="$(dirname $(readlink -f $T4D_ROOT_PATH/manifest.xml))"
    cd $TEAM_PATH
    git pull
fi
